language: android
android:
  components:
    - build-tools-23.0.0
    - android-23
    - android-22
    - android-21
    - android-19
    - android-16
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android\-sdk\-license\-.*'
